Problems with role and user classes fixed
korolov-vv/goit-notes pull request #11
Opened 2021-08-31 17:59 UTC by Burkov1982

2021-08-31 22:54 UTC, korolov-vv approved these changes

2021-08-31 23:53 UTC, korolov-vv requested changes

2021-08-31 23:53 UTC, korolov-vv commented on src/main/java/ua/goit/goitnotes/service/NoteService.java
> +    public NoteDTO findByName(String title) {
По идее сервисы тоже должны возвращать Optional<T> т.к. при нынешней реализации мы везде будет отлавливать ошибки

2021-09-01 08:42 UTC, Burkov1982 commented on src/main/java/ua/goit/goitnotes/service/NoteService.java
> +    public NoteDTO findByName(String title) {
То есть, сервисы будут возвращать Optional ДАО, но где тогда будет происходить конвертация из ДАО в ДТО?

2021-09-01 13:53 UTC, closed without merging