add service interfaces
korolov-vv/goit-notes pull request #4
Opened 2021-08-29 16:57 UTC by HannaRaus

2021-08-29 18:36 UTC, DenisAndrieiew commented on src/main/java/ua/goit/goitnotes/service/processors/MarkdownProcessor.java
> +    String getMarkdown(String html);
Я не вижу случаев, когда нам потребуется преобразование из html в markdown. Это выглядит лишним методом

2021-08-29 18:38 UTC, DenisAndrieiew commented on src/main/java/ua/goit/goitnotes/service/validators/Validator.java
> +    boolean validate(T entity);
класс будет возвращать объект ValidateResponse

2021-08-29 18:39 UTC, DenisAndrieiew commented on src/main/java/ua/goit/goitnotes/service/Service.java
> +
для User может понадобиться findByName(String name)

2021-08-30 01:28 UTC, korolov-vv requested changes

2021-08-30 01:28 UTC, korolov-vv commented on src/main/java/ua/goit/goitnotes/service/Service.java
> +
Согласен, но я такой метод называл в своих рботах findByUniqueValue(String value) и тогда такой метод модно реальзовать и для заметок и для польхователя и для всего что будет в будущем создаваться

2021-08-30 01:28 UTC, korolov-vv commented on src/main/java/ua/goit/goitnotes/service/processors/MarkdownProcessor.java
> +    String getMarkdown(String html);
А когда заметку нужно будет редактировать? Всо правильно - не лишний

2021-08-30 01:28 UTC, korolov-vv commented on src/main/java/ua/goit/goitnotes/service/validators/Validator.java
> +    boolean validate(T entity);
Согласен, метод доджен возвращать объект, т.к. мы же дальше не просто тру фолс передаем, а и менно ремпонм будем отправлять

2021-08-30 03:30 UTC, DenisAndrieiew commented on src/main/java/ua/goit/goitnotes/service/processors/MarkdownProcessor.java
> +    String getMarkdown(String html);
Заметка хоанится в базе в виде markdown и редактируется as is, в textarea. Конвертация в html нужна только для отрисовки у клиента.

2021-08-30 08:52 UTC, HannaRaus commented on src/main/java/ua/goit/goitnotes/service/processors/MarkdownProcessor.java
> +    String getMarkdown(String html);
Прибрала метод getMarkdown()

2021-08-30 08:53 UTC, HannaRaus commented on src/main/java/ua/goit/goitnotes/service/validators/Validator.java
> +    boolean validate(T entity);
Змінила ретурн значення, змінила параметр прийому на стрінгу, так як з форми ми дізтаємо саме її

2021-08-30 08:59 UTC, HannaRaus commented on src/main/java/ua/goit/goitnotes/service/Service.java
> +
Я б не робила метод findByName(String name) для усіх сервісів. Бо він потрібен саме юзеру, а іншим прийдеться робити заглушку. Краще його зробити саме у юзер сервісі, бо цей метод тільки для нього характерний.

findByUniqueValue(String value) теж не робила. 1 - по назві не зрозуміло що там відбувається, 2 - це буде метод, який використовується тільки юзером, усі інші мають зробити заглушку.

2021-08-30 12:06 UTC, korolov-vv commented on src/main/java/ua/goit/goitnotes/service/Service.java
> +
Если этот метод реализовать только у юзера, мы тогда нам нунжно будет создавать еще один интерфейс, чтоб использовать его дальше - для такой маленькой программы - слишком много интерфейсов. Плюс у каждой сущности есть уникальное знчение - у заметок это тайтл, поэтому можно искать по тайтлу и это удобнее чем искать по айди

2021-08-30 14:53 UTC, HannaRaus commented on src/main/java/ua/goit/goitnotes/service/Service.java
> +
не потрібен зайвий інтерфейс, просто реалізація метода findByName() у юзер сервіс. Але якщо буде пошук по тайтлу, то можу додати findByName() в інтерфейс сервісу

2021-08-30 14:59 UTC, korolov-vv commented on src/main/java/ua/goit/goitnotes/service/Service.java
> +
Тоді зроби так

2021-08-30 15:28 UTC, korolov-vv approved these changes

2021-08-30 15:28 UTC, merged