Tools for working with DB added
korolov-vv/goit-notes pull request #6
Opened 2021-08-30 05:59 UTC by Burkov1982

2021-08-30 09:42 UTC, HannaRaus commented on src/main/java/ua/goit/goitnotes/dto/NoteDTO.java
> +    private String userName;
я б винесла @Getter & @Setter над класом, щоб не було повторення.

2021-08-30 09:44 UTC, HannaRaus commented on src/main/java/ua/goit/goitnotes/model/entity/NoteDAO.java
> +    @Setter
теж саме, геттери та сеттери над класом.

2021-08-30 09:45 UTC, HannaRaus commented on src/main/java/ua/goit/goitnotes/model/entity/NoteDAO.java
> +public class NoteDAO {
Потрібен ще equal&hashCode

2021-08-30 09:46 UTC, HannaRaus commented on src/main/java/ua/goit/goitnotes/model/entity/NoteDAO.java
> +    @ManyToOne(fetch = FetchType.EAGER)
Навіщо FetchType.EAGER?

2021-08-30 09:47 UTC, HannaRaus commented on src/main/java/ua/goit/goitnotes/model/entity/User.java
> +    @Setter
теж саме з сеттерами та геттерами

2021-08-30 13:23 UTC, korolov-vv requested changes

2021-08-30 13:23 UTC, korolov-vv commented on src/main/java/ua/goit/goitnotes/dto/NoteDTO.java
> +    private String userName;
Плюс конструктор тоже объяви в аннотации - @NoArgsConstructor

2021-08-30 13:23 UTC, korolov-vv commented on src/main/java/ua/goit/goitnotes/model/entity/Enums/AccessType.java
> +public enum AccessType {
Этот классс Таня делала, ее изменения уже вмерджены, нужно синхронизироваться

2021-08-30 13:23 UTC, korolov-vv commented on src/main/java/ua/goit/goitnotes/model/entity/NoteDAO.java
> +public class NoteDAO {
@NoArgsConstructor в аннотации

2021-08-30 13:23 UTC, korolov-vv commented on src/main/java/ua/goit/goitnotes/service/NoteService.java
> +            throw new UsernameNotFoundException("Note with specified ID not found");
Этот exception я бы назвал ObjectNotFoundException, потому что странно, что в методе с запиской UserNameMotFound...... И в меседже тогда писать "Object 'note' with specified ID not found"

2021-08-30 22:49 UTC, korolov-vv requested changes

2021-08-30 22:49 UTC, korolov-vv commented on src/main/java/ua/goit/goitnotes/service/UserService.java
> +    public User findByName(String name) {
Анна дела в своем интерфейсе этот метод, так что здесь должно быть @Override

2021-08-30 22:49 UTC, korolov-vv commented on src/main/java/ua/goit/goitnotes/service/UserService.java
> +public class UserService implements Service<User>{
Не хватает аннотации @Service над классом

2021-08-30 22:49 UTC, korolov-vv commented on src/main/java/ua/goit/goitnotes/service/RoleService.java
> +public class RoleService implements Service<UserRole> {
@Service

2021-08-30 22:49 UTC, korolov-vv commented on src/main/java/ua/goit/goitnotes/service/NoteService.java
> +public class NoteService implements Service<NoteDTO> {
@Service

2021-08-30 22:49 UTC, korolov-vv commented on src/main/java/ua/goit/goitnotes/model/entity/User.java
> +    @OneToOne(mappedBy = "users")
здесь опечатка - должно быть user

2021-08-30 22:49 UTC, korolov-vv commented on src/main/java/ua/goit/goitnotes/model/entity/User.java
> +    @OneToMany(mappedBy = "users")
здесь опечатка - должно быть user

2021-08-31 11:54 UTC, korolov-vv approved these changes

2021-08-31 11:54 UTC, merged